"use client";
import type { Metadata } from "next";
import { Provider } from "react-redux";
import "./globals.css";
import { cn } from "@/lib/utils";

import localFont from "next/font/local";
import background from "../../public/background.png";
import { store } from "@/store/store";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const belezza = localFont({
  src: [
    { path: "../../public/fonts/Belleza/Belleza-Regular.ttf", weight: "400" },
  ],
  variable: "--belleza",
  display: "swap",
  adjustFontFallback: false,
});

const beLoveYaLikeASister = localFont({
  src: [
    {
      // path: "./fonts/Love_Ya_Like_A_Sister/LoveYaLikeASister-Regular.ttf",
      path: "../../public/fonts/Love_Ya_Like_A_Sister/LoveYaLikeASister-Regular.ttf",
      weight: "400",
    },
  ],
  variable: "--beLoveYaLikeASister",
  display: "swap",
  adjustFontFallback: false,
});

const crimson = localFont({
  src: [
    {
      // path: "./fonts/Love_Ya_Like_A_Sister/LoveYaLikeASister-Regular.ttf",
      path: "../../public/fonts/Crimson_Text/CrimsonText-Regular.ttf",
      weight: "400",
    },
  ],
  variable: "--crimson",
  display: "swap",
  adjustFontFallback: false,
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={cn(
        //   "font-sans antialiased bg-[url('/background-chalk1.png')] h-screen bg-cover bg-no-repeat  overflow-y-scroll no-scrollbar",
        //   fontSans.variable
        // )}

        // className={cn(
        //   "antialiased bg-[url('/background-chalk1.png')] h-px[3890px] mb-44 bg-cover bg-no-repeat  overflow-hidden no-scrollbar",
        //   beLoveYaLikeASister.variable,
        //   crimson.variable,
        //   belezza.variable
        // )}

        className={cn(
          "fixed h-[3840px] max-h-full w-[2160px]  max-w-full bottom-0 overflow-hidden no-scrollbar bg-white border-0 rounded-xl border-white antialiased bg-[url('/background-chalk1.png')] bg-cover bg-no-repeat",
          beLoveYaLikeASister.variable,
          crimson.variable,
          belezza.variable
        )}
      >
        <Provider store={store}>{children}</Provider>
        {/* <Provider store={store}> */}
        {/* <div className="text-6xl m-4 text-black flex flex-col items-stretch justify-self-auto">
            Hallo1
          </div> */}
        {/* </Provider> */}
      </body>
    </html>
  );
}
